# Generated by Django 4.0.3 on 2022-03-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('photos', models.ImageField(default='#', upload_to='images/')),
                ('describe', models.TextField(blank=True, null=True)),
                ('chapter', models.IntegerField(blank=True, null=True)),
                ('season', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
